version: '3.7'

services:
  get_rate:
    build: ./app
    command: python3 manage.py get_rate
    env_file:
      - ./.env.prod
    depends_on:
      - db
  web:
    build: ./app
    command: gunicorn currency_converter.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    volumes:
      - static_volume:/usr/src/app/staticfiles
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 8085:80
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume: