# Generated by Django 3.0 on 2019-12-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_ready', models.BooleanField(default=False)),
                ('rate_url', models.CharField(default='', max_length=255)),
                ('main_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Currency')),
            ],
        ),
    ]
