# Generated by Django 3.0 on 2019-12-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191210_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='last_error',
            field=models.CharField(default='', max_length=255),
        ),
    ]
